const AUTH = {
  LOGIN: "AUTH_LOGIN",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAIL: "AUTH_LOGIN_FAIL",
  LOGOUT: "AUTH_LOGOUT",
  LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  LOGOUT_FAIL: "AUTH_LOGOUT_FAIL",
};

export { AUTH };
